# $Id: Makefile,v 1.1 2005/06/17 16:23:41 linderot Exp $
#

png: avgb.png\
	avgnaw.png\
	avgnsw.png\
	avgpw.png\
	equivb.png\
	equivpp.png\
	equivrt.png\
	knapsack.png\
	maxb.png\
	minb.png\
	opp.png\
	sumc.png\
	sums.png\
	sumu.png

%.png: %.tex
	./textopng $*
