MWWorker Class Reference
#include <MWWorker.h>
Public Member Functions
MWWorker ()
Default constructor.
virtual ~MWWorker ()
Default Destructor.
void go (int argc, char *argv[])
Giddyap!
MWReturn do_benchmark_cmd ()
MWReturn worker_mainloop_oneshot ()
int send_update_message ()
void check_update_message ()
virtual void unpack_update ()
Public Attributes
int workerid
Static Public Attributes
static MWRMComm * RMC
Our RM / Comm class. Used here only for communication.
Protected Member Functions
virtual void pack_worker_initinfo ()
virtual MWReturn unpack_init_data ()=0
virtual void execute_task (MWTask *)=0
virtual double benchmark (MWTask *t)
virtual void unpack_driver_task_data (void)
MWReturn greet_master ()
void worker_mainloop ()
void suicide ()
Die!!!!!!
Protected Attributes
int master
The task ID of the master - used for sending messages.
MWTask * workingTask
MWTask * controlTask
char mach_name [64]
The name of the machine the worker is running on.
char master_mach_name [64]
The name of the master machine.
Detailed Description
This is the worker class that performs the tasks in the opportunistic condor environment. It is an oppressed worker class in that in simply executes the tasks given to it and reports the results back to the master. { :-)}
Capitalist stooges who wish to create an application must derive a class from this class, and implement the following two methods
{itemize} unpack_init_data() execute_task() {itemize}
See also
MWDriver
MWWorker
Author
Mike Yoder, modified by Jeff Linderoth and Jean-Pierre Goux
Member Function Documentation
benchmark()
double MWWorker::benchmark (MWTask * t) [protected], [virtual]
This function performs the action that happens once the worker receives a subtask. Subtask id starts at 0 and ends at n-1 subtasks.
Deprecated - changing subtask model for container of tasks model The number of subtasks per worker is defined here. If this function is not implemented, then data streaming/subtasks is turned off and Master-Worker executes normally.
Deprecated - changing subtask model for container of tasks modelRun a benchmark, given an MWTASK. The default implementation is to call {verbatim} execute_task(t) {verbatim} and return 1.0/(Task Time) as a benchmark of how fast the machine is
References execute_task().
Referenced by greet_master(), and pack_worker_initinfo().
execute_task()
virtual void MWWorker::execute_task (MWTask *) [protected], [pure virtual]
This function performs the actions that happen once the Worker finds out there is a task to do. You will need to cast the MWTask * to a pointer of the Task type derived for your application. For example
{verbatim} Task_Fib *dt = dynamic_cast<Task_Fib *> (t); assert(dt); {verbatim}
Referenced by benchmark(), pack_worker_initinfo(), and worker_mainloop().
greet_master()
MWReturn MWWorker::greet_master () [protected]
This is run before the worker_mainloop(). It prints a message that the worker has been spawned, sends the master an INIT message, and awaits a reply from the master, upon which it calls unpack_init_data().
References benchmark(), MWRMComm::bufinfo(), MWRMComm::exit(), MWRMComm::initsend(), mach_name, master, master_mach_name, MWRMComm::pack(), pack_worker_initinfo(), MWRMComm::recv(), RMC, MWRMComm::send(), MWRMComm::unpack(), unpack_init_data(), MWTask::unpack_work(), and workingTask.
Referenced by go(), unpack_driver_task_data(), and worker_mainloop().
pack_worker_initinfo()
virtual void MWWorker::pack_worker_initinfo () [inline], [protected], [virtual]
Here we might in the future pack some useful information about the specific machine on which we're running. Right now, all workers are equal, and we pass only the hostname.
There must be a `matching` unpack_worker_initinfo() in the MWDriver class.
References benchmark(), execute_task(), and unpack_init_data().
Referenced by greet_master().
unpack_driver_task_data()
virtual void MWWorker::unpack_driver_task_data (void) [inline], [protected], [virtual]
If you have some driver data that you would like to use on the worker in order to execute the task, you should unpack it here.
References greet_master(), suicide(), and worker_mainloop().
Referenced by worker_mainloop().
unpack_init_data()
virtual MWReturn MWWorker::unpack_init_data () [protected], [pure virtual]
This unpacks the initial data that is sent to the worker once the master knows that he has started.
There must be a `matching` pack_worker_init_data() in the MWDriver class derived for your application.
Referenced by greet_master(), pack_worker_initinfo(), and worker_mainloop().
worker_mainloop()
void MWWorker::worker_mainloop () [protected]
This sits in a loop in which it asks for work from the master and does the work. Maybe we should name this class GradStudent. { :-)}
References MWRMComm::bufinfo(), execute_task(), MWRMComm::exit(), greet_master(), MWRMComm::initsend(), mach_name, master, MWTask::number, MWRMComm::pack(), MWTask::pack_results(), MWRMComm::recv(), RMC, MWRMComm::send(), suicide(), MWTask::taskType, MWRMComm::unpack(), unpack_driver_task_data(), unpack_init_data(), MWTask::unpack_work(), and workingTask.
Referenced by go(), and unpack_driver_task_data().
Member Data Documentation
workingTask
MWTask* MWWorker::workingTask [protected]
The task instance that a worker will use for packing/unpacking information from the master
Referenced by go(), greet_master(), MWWorker(), and worker_mainloop().
The documentation for this class was generated from the following files:
MWWorker.h
MWWorker.C