MWTask Class Reference
#include <MWTask.h>
Public Member Functions
MWTask ()
Default constructor.
virtual ~MWTask ()
Default Destructor.
void initGroups (int num)
void addGroup (int num)
add task to a workclass/group
void deleteGroup (int num)
remove a task from a workclass/group
bool doesBelong (int num)
MWGroup * getGroup ()
 Packing and Unpacking
The user must pack and unpack the contents of the class so that it can be sent to the worker and back. These functions will make RMC->pack() and RMC->unpack() calls.
virtual void pack_work (void)=0
Pack the work portion of the task.
virtual void unpack_work (void)=0
Unpack the work portion of the task.
virtual void pack_results (void)=0
Pack the result portion of the task.
virtual void unpack_results (void)=0
Unpack the result portion of the task.
virtual void pack_subresults (int)
Pack the subresult portion of the task.
virtual void unpack_subresults (int)
Unpack the subresult portion of the task.
virtual void printself (int level=60)
Dump this task to the screen.
 Checkpointing Utilities
These two functions are used when checkpointing. Simply put, they write/read the state of the task to this file pointer provided.
virtual void write_ckpt_info (FILE *fp)
virtual void read_ckpt_info (FILE *fp)
void write_group_info (FILE *fp)
void read_group_info (FILE *fp)
Public Attributes
int number
The task's number.
int randomstop
int numsubtask
MWTaskType taskType
The task's type.
MWGroup * group
 Time and usage data
double working_time
double cpu_time
 List management
The task also has pointers that aid for managing the list of tasks to be done
MWWorkerID * worker
A pointer to the worker ID executing this task (NULL if none)
Static Public Attributes
static MWRMComm * RMC
Detailed Description
This the class that represents a unit of work.
The task consits of two main components. The `work` to be done, and the `result` of the completed task. In order to create an application, the user must specify methods for packing and unpacking both the `work` and `result` portions of the task. The user is not responsible for initializing the send or for packing the task's number
When the task is being serviced by a worker, it contains a link to the ID of that instance of the worker.
See also
MWDriver
MWWorker
Author
Mike Yoder, modified by Jeff Linderoth and Jean-Pierre Goux
Member Function Documentation
read_ckpt_info()
virtual void MWTask::read_ckpt_info (FILE * fp) [inline], [virtual]
Read the state of this task from a FILE* (overwriting any existing state
References addGroup(), deleteGroup(), and worker.
Referenced by MWDriver::restart_from_ckpt().
write_ckpt_info()
virtual void MWTask::write_ckpt_info (FILE * fp) [inline], [virtual]
Write the state of this task out to a FILE*
Referenced by MWDriver::checkpoint(), and MWDriver::restart_from_ckpt().
Member Data Documentation
cpu_time
double MWTask::cpu_time
The amount of user+system time taken by this task, measured from start to finish of the 'execute_task' function.
Referenced by MWDriver::handle_hostresume().
working_time
double MWTask::working_time
The time (wall clock) that it takes to run the 'execute_task' function on the worker's side.
Referenced by MWDriver::handle_hostresume().
The documentation for this class was generated from the following files:
MWTask.h
MWTask.C