MWRMComm Class Reference
Public Member Functions
MWRMComm ()
virtual ~MWRMComm ()
Destructor...
double get_bytes_packed () const
double get_bytes_unpacked () const
virtual int recv_all (int from_whom, int msgtag)=0
virtual int setrbuf (int bid)=0
virtual int freebuf (int bid)=0
virtual int next_buf ()=0
virtual MWList< void > * recv_buffers ()=0
 A. Resource Management Functions
Here are all the methods you could want to have for managing a set of machines. See each method for details...
virtual void exit (int exitval)
virtual int setup (int argc, char *argv[], int *my_id, int *master_id)=0
virtual int config (int *nhosts, int *narches, MWWorkerID ***w)
virtual int start_worker (MWWorkerID *w)=0
virtual int init_beginning_workers (int *nworkers, MWWorkerID ***workers)=0
virtual int removeWorker (MWWorkerID *w)=0
 B. Checkpointing Functions
virtual int write_checkpoint (FILE *fp)
virtual int read_checkpoint (FILE *fp)
virtual int read_RMstate (FILE *fp)
virtual int write_RMstate (FILE *fp)
virtual int restart_beginning_workers (int *num, MWWorkerID ***tempWorkers, MWmessages msg)=0
 The Communication Routines
These message passing routines are very closely modeled on PVM's message passing facility. They are, however, pretty generic in that any message passing interface should be able to implement them.
virtual int initsend (int encoding=0)=0
virtual int send (int to_whom, int msgtag)=0
virtual int recv (int from_whom, int msgtag)=0
virtual int nrecv (int from_whom, int msgtag)
virtual int bufinfo (int buf_id, int *len, int *tag, int *from)=0
virtual void who (int *wh)=0
virtual void hostadd ()
 Pack Functions
In the following pack() functions, there are some common themes. First, each stuffs some data into a buffer to be sent. The nitem parameter is just a count of the number of items. The stride parameter specifies which items to pack. 1 implies all, 2 would be every 2nd item, 3 is every 3rd item, etc.
The return value is user defined. It should be standardized, but I'll do that later.
virtual int pack (const char *bytes, int nitem, int stride=1)=0
Pack some bytes.
virtual int pack (const float *f, int nitem, int stride=1)=0
float
virtual int pack (const double *d, int nitem, int stride=1)=0
double
virtual int pack (const int *i, int nitem, int stride=1)=0
int
virtual int pack (const unsigned int *ui, int nitem, int stride=1)=0
unsigned int
virtual int pack (const short *sh, int nitem, int stride=1)=0
short
virtual int pack (const unsigned short *ush, int nitem, int stride=1)=0
unsigned short
virtual int pack (const long *l, int nitem, int stride=1)=0
long
virtual int pack (const unsigned long *ul, int nitem, int stride=1)=0
unsigned long
virtual int pack (const char *string)=0
Pack a NULL-terminated string.
 Unpack Functions
These unpack functions unpack data packed with the pack() functions. See the pack() functions for more details.
virtual int unpack (char *bytes, int nitem, int stride=1)=0
Unpack some bytes.
virtual int unpack (float *f, int nitem, int stride=1)=0
float
virtual int unpack (double *d, int nitem, int stride=1)=0
double
virtual int unpack (int *i, int nitem, int stride=1)=0
int
virtual int unpack (unsigned int *ui, int nitem, int stride=1)=0
unsigned int
virtual int unpack (short *sh, int nitem, int stride=1)=0
short
virtual int unpack (unsigned short *ush, int nitem, int stride=1)=0
unsigned short
virtual int unpack (long *l, int nitem, int stride=1)=0
long
virtual int unpack (unsigned long *ul, int nitem, int stride=1)=0
unsigned long
virtual int unpack (char *string)=0
Unpack a NULL-terminated string.
Protected Attributes
MWList< void > * recv_buf_list
double bytes_packed_
Keeps the number of bytes packed.
double bytes_unpacked_
Holds the number of bytes unpacked.
Friends
class MWDriver
C. Executable Management Interface functions
int exec_classes
int num_arches
char ** arch_class_attributes
int num_executables
int tempnum_executables
struct RMC_executable ** worker_executables
bool worker_checkpointing
Would you like the workers to be checkpointed.
int * MW_exec_class_num_workers
void set_num_exec_classes (int num)
int get_num_exec_classes ()
void set_num_arch_classes (int n)
void set_arch_class_attributes (int arch_class, const char *attr)
int get_num_arch_classes ()
void set_num_executables (int num)
int get_num_executables ()
void add_executable (int exec_class, int arch_class, char *exec_name, char *requirements)
void add_executable (const char *exec_name, const char *requirements)
virtual char * process_executable_name (char *exec_name, int ex_cl, int num_arc)
virtual void set_worker_checkpointing (bool wc)
D. Host Management Members
int target_num_workers
int * exec_class_target_num_workers
int hostinc_
void set_target_num_workers (int num_workers)
void set_target_num_workers (int exec_class, int num_workers)
int get_target_num_workers (int exec_class=-1)
void set_worker_increment (int newinc)
int get_worker_increment () const
virtual int hostaddlogic (int *num_workers)=0
Constructor & Destructor Documentation
MWRMComm()
MWRMComm::MWRMComm ()
Constructor. Sets data to -1's.
Member Function Documentation
add_executable()
void MWRMComm::add_executable (int exec_class, int arch_class, char * exec_name, char * requirements)
Set the name of the binary and the requirements string for an arch class. Technically, the requirements string is not needed for MWPvmRC - it is defined in the submit file. It is needed in the MWFileRC, however, for job submission.
Parameters
arch_class This specifies which arch class the above requirements will apply to.
exec_name The name of the worker executable for this arch class.
requirements A string containing the `requirements` attribute of a given arch class of workers. This will be something that can be used in a submit file, like `(arch == \`INTEL" && opsys == "SOLARIS26")"
bufinfo()
virtual int MWRMComm::bufinfo (int buf_id, int * len, int * tag, int * from) [pure virtual]
Provide info on the message just received
Referenced by MWDriver::go(), MWWorker::greet_master(), MWWorker::suicide(), and MWWorker::worker_mainloop().
config()
virtual int MWRMComm::config (int * nhosts, int * narches, MWWorkerID *** w) [inline], [virtual]
This returns the state of the `virtual machine` - aka the set of workers under the master's control.
Parameters
nhosts The number of hosts
narches The number of architechture classes
w A pointer to a pointer to an array of pointers. This should be NULL when called; config() will allocate the memory using new and return it to you. Don't forget to delete not only the elements in that array, but also the array itself. The array will have nhosts elements, and they will each represent a worker machine.
Returns
0 on success, -1 on error.
exit()
virtual void MWRMComm::exit (int exitval) [virtual]
System shutdown. Does not return.
Parameters
exitval The value to call ::exit() with
Referenced by MWDriver::addSortedTasks(), MWDriver::addTasks(), MWDriver::go(), MWWorker::greet_master(), MWWorker::suicide(), and MWWorker::worker_mainloop().
get_num_arch_classes()
int MWRMComm::get_num_arch_classes ()
Return the number of arch classes
get_num_exec_classes()
int MWRMComm::get_num_exec_classes ()
Returns the above number
Referenced by MWDriver::delete_tasks_worse_than(), and MWDriver::get_workers_head().
hostadd()
virtual void MWRMComm::hostadd () [inline], [virtual]
Needed only for MW-Independent
Referenced by MWDriver::addSortedTasks().
hostaddlogic()
virtual int MWRMComm::hostaddlogic (int * num_workers) [protected], [pure virtual]
This will figure out if we need to ask for more hosts or remove hosts. It is called whenever a host is added or removed from the system, or set_target_num_workers() is called.
Parameters
num_workers A pointer to an array of length num_arches that contains the number of workers for each arch class.
Returns
If we have more workers than we need, we return a positive number as the `excess` that can be deleted.
Referenced by MWDriver::delete_tasks_worse_than().
init_beginning_workers()
virtual int MWRMComm::init_beginning_workers (int * nworkers, MWWorkerID *** workers) [pure virtual]
This routine is used to start up multiple workers at the beginning of a run. It should only be called one time. It basically does a config() to find out what machines are available, and then starts a worker on each of them. You may want to check the implementations for details...
Parameters
nworkers The number of workers at the start (returned!)
workers A pointer to a pointer to an array of MWWorkerID pointers. The memory management for this is the same as it is for the config() call - it should be null when called and will point to allocated memory when it comes back.
Returns
0 on success, -1 on failure
Referenced by MWDriver::go().
initsend()
virtual int MWRMComm::initsend (int encoding = 0) [pure virtual]
Initialize a buffer for sending some data.
Parameters
encoding Defined by each application. 0 = default
Referenced by MWDriver::get_workers_head(), MWDriver::go(), MWWorker::greet_master(), MWDriver::handle_benchmark(), MWDriver::handle_checksum(), MWDriver::refreshWorkers(), MWDriver::stop_work(), and MWWorker::worker_mainloop().
nrecv()
virtual int MWRMComm::nrecv (int from_whom, int msgtag) [inline], [virtual]
non-blocking receive. This is the same as recv except it returns the NO_MESSAGE tag instead of blocking if there is no data in the buffer
Referenced by MWWorker::suicide().
process_executable_name()
virtual char* MWRMComm::process_executable_name (char * exec_name, int ex_cl, int num_arc) [virtual]
If the RM software needs to `process` the executable name in some way, this is done here.
read_checkpoint()
virtual int MWRMComm::read_checkpoint (FILE * fp) [virtual]
Read in restart information from a FILE *
Referenced by MWDriver::restart_from_ckpt().
read_RMstate()
virtual int MWRMComm::read_RMstate (FILE * fp) [virtual]
Some Low level specific read/write functions
recv()
virtual int MWRMComm::recv (int from_whom, int msgtag) [pure virtual]
Receive some data that has been packed. Should make this more PVM-independent; will do this sometime.
Parameters
from_whom From a specific source; -1 is from all
msgtag With a certain tag; -1 is all.
Referenced by MWDriver::go(), MWWorker::greet_master(), and MWWorker::worker_mainloop().
removeWorker()
virtual int MWRMComm::removeWorker (MWWorkerID * w) [pure virtual]
Remove a worker from the virtual machine. This call will delete w, so don't reference that memory again!
Parameters
w The MWWorkerID of the machine to remove.
Returns
0 on success, a negative number on failure
Referenced by MWDriver::delete_tasks_worse_than(), MWDriver::handle_benchmark(), MWDriver::handle_checksum(), MWDriver::handle_taskexit(), and MWDriver::refreshWorkers().
restart_beginning_workers()
virtual int MWRMComm::restart_beginning_workers (int * num, MWWorkerID *** tempWorkers, MWmessages msg) [pure virtual]
A function to restart the workers. This is called at restart from a ckpt file and it is meant to re-init all the workers.
Referenced by MWDriver::go().
send()
virtual int MWRMComm::send (int to_whom, int msgtag) [pure virtual]
Send the data that has been packed.
Parameters
to_whom An identifier for the recipient
msgtag A 'tag' to identify that type of message
Referenced by MWDriver::get_workers_head(), MWDriver::go(), MWWorker::greet_master(), MWDriver::handle_benchmark(), MWDriver::handle_checksum(), MWDriver::refreshWorkers(), MWDriver::stop_work(), MWWorker::suicide(), and MWWorker::worker_mainloop().
set_arch_class_attributes()
void MWRMComm::set_arch_class_attributes (int arch_class, const char * attr)
set the arch attribute
set_num_arch_classes()
void MWRMComm::set_num_arch_classes (int n)
Set the number of arch classes
set_num_exec_classes()
void MWRMComm::set_num_exec_classes (int num)
Set the number of executable classes
set_num_executables()
void MWRMComm::set_num_executables (int num)
Set the number of executables
set_target_num_workers()
void MWRMComm::set_target_num_workers (int num_workers)
Set a `target` number of workers across all arches. This is useful if you don't care how many you get of each arch...
Parameters
num_workers The target number of workers
Referenced by MWDriver::get_workers_head().
set_worker_checkpointing()
virtual void MWRMComm::set_worker_checkpointing (bool wc) [virtual]
Set whether or not you would like worker checkpointing (if the CommRM implementation has the capability)
set_worker_increment()
void MWRMComm::set_worker_increment (int newinc)
The RMComm will requests this many workers at a time
setup()
virtual int MWRMComm::setup (int argc, char * argv[], int * my_id, int * master_id) [pure virtual]
Initialization of the master process. This will be called one time only when the master starts up.
Returns
0 on success, -1 on failure
Referenced by MWWorker::go(), and MWDriver::go().
start_worker()
virtual int MWRMComm::start_worker (MWWorkerID * w) [pure virtual]
Start a worker on a machine that has been given to you. This is really only important if the process of starting a worker is two-stage. For instance, in pvm, you first get a machine. THEN you have to spawn an executable on that machine. For something like MW-files, once you get a worker it already has the executable started on it. In that case this will basically be a no-op.
Parameters
w A pointer to a MWWorkerID. This must point to allocated memory. It is filled with info like the machine name, id2, and the arch.
Returns
id2 on success, -1 on failure
Referenced by MWDriver::go().
who()
virtual void MWRMComm::who (int * wh) [pure virtual]
For some system events like HOSTDELETE, TASKEXIT, etc, this will tell who was affected
Referenced by MWDriver::handle_checksum(), MWDriver::handle_hostdel(), MWDriver::handle_hostresume(), MWDriver::handle_hostsuspend(), MWDriver::handle_taskexit(), and MWDriver::stop_work().
write_checkpoint()
virtual int MWRMComm::write_checkpoint (FILE * fp) [virtual]
Write out internal state to a FILE *
Referenced by MWDriver::checkpoint().
Member Data Documentation
arch_class_attributes
char** MWRMComm::arch_class_attributes [protected]
The arch attributes
exec_class_target_num_workers
int* MWRMComm::exec_class_target_num_workers [protected]
The desired number of workers, exec_class wise
exec_classes
int MWRMComm::exec_classes [protected]
The number of exec classes
hostinc_
int MWRMComm::hostinc_ [protected]
The current
num_arches
int MWRMComm::num_arches [protected]
The number of different arch classes.
num_executables
int MWRMComm::num_executables [protected]
The number of executables
recv_buf_list
MWList<void>* MWRMComm::recv_buf_list [protected]
When investigating the master-side bottleneck problem, we realized that sometimes the master can't handle all the messages sent from the many masters and the RMComm layer. The messages are accumulated in the RMComm layer's buffer (especially in the case of using MW-CondorPvm), but the master can't see them, not to mention process them or delete useless messages. This makes the master unable to accormodate the chanegs in the environment, also makes most of the workers waiting for new tasks.
One way to deal with this situation is to pull all the messages in the underlying message passing layer and let the master buffer them by itself, to separate the message receiving and message processing steps.
Thus we will introduce a FIFO list of buf_id (list of *int), each of the buf_id points to a message buffer in PVM (and likewise in the other RMComms). The original message processing steps are: RMC->recv() RMC->bufinfo() RMC->unpack(), RMC->unpack() And now the process will be the same, but implementation is different: RMC->recv_all() pull all messages out (in a non-blocking way) and put each message's buf_id into the FIFO list. RMC->recv() blocking recv RMC->bufinfo() examine the buf_info of the buffer with given buf_id RMC->setrbuf() will be used to switch the active receive buffer RMC->freebuf() will be used to free useless receive buffer RMC->unpack()
All recv will via the buffer_list now!
target_num_workers
int MWRMComm::target_num_workers [protected]
The desired number of workers
worker_executables
struct RMC_executable** MWRMComm::worker_executables [protected]
An array containing the { full} pathnames of the executables. Element 0 is for arch `0`, element 1 is for arch `1`, etc. Usually read in get get_userinfo().
The documentation for this class was generated from the following file:
MWRMComm.h