MWDriver Class Reference
#include <MWDriver.h>
Public Member Functions
MWDriver ()
Default constructor.
virtual ~MWDriver ()
void go (int argc, char *argv[])
void go ()
virtual void printresults ()
void reassignSuspendedTask (MWList< MWTask > *running, MWWorkerID *w)
void reassignIdleTask (MWList< MWWorkerID > *workers, MWWorkerID *w)
int matchTask (void *arg1, void *arg2)
MWWorkerID * numberworker (void *arg1, void *arg2)
void prepare_update (int mode)
virtual void pack_update ()
int send_update_message ()
int send_update_message_to (int worker)
 C. Worker Policy Management
void set_suspension_policy (MWSuspensionPolicy)
int set_machine_ordering_policy (MWMachineOrderingPolicy)
Sets the machine ordering policy.
 D. Event Handling Methods
In the case that the user wants to take specific actions when notified of processors going away, these methods may be reimplemented. Care must be taken when reimplementing these, or else things may get messed up.
Probably a better solution in the long run is to provide users hooks into these functions or something.
Basic default functionality that updates the known status of our virtual machine is provided.
virtual MWReturn handle_benchmark (MWWorkerID *w)
virtual void handle_hostdel ()
virtual void handle_hostsuspend ()
virtual void handle_hostresume ()
virtual void handle_taskexit ()
virtual void handle_checksum ()
 Benchmarking
We now have a user-defined benchmarking phase. The user can `register` a task that is sent to each worker upon startup. This way, the user knows which machines are fastest, and MW can perform can automatic `normalization` of the equivalent CPU time.
void register_benchmark_task (MWTask *t)
MWTask * get_benchmark_task ()
Static Public Attributes
static MWRMComm * RMC
Protected Member Functions
 A. Pure Virtual Methods
These are the methods from the MWDriver class that a user { must} reimplement in order to have to create an application.
virtual MWReturn get_userinfo (int argc, char *argv[])=0
virtual MWReturn setup_initial_tasks (int *n, MWTask ***task)=0
virtual MWReturn act_on_completed_task (MWTask *)=0
virtual MWReturn act_on_starting_worker (MWWorkerID *w)
virtual MWReturn pack_worker_init_data (void)=0
virtual void unpack_worker_initinfo (MWWorkerID *w)
virtual void pack_driver_task_data (void)
 Data streaming/subtasks
These are the methods that must be implemented to enable data streaming/ subtasks.
act_on_completed_subtask()
MWWorker::execute_subtask
MWWorker::set_num_subtask
MWTask::pack_subresults
MWTask::unpack_subresults
A subtask is identified by a MWTask and a subtask id. The subtask id starts at 0 and ends at n-1 subtasks.
When subtasks are enabled, the Master sends the task to the Worker as usual. But instead of calling execute_task once, execute_subtask is called once per subtask id (starting at 0). At the end of each call, the result will be returned to the Master. After all subtasks have completed, the Master is notified that the Task has completed.
virtual MWReturn act_on_completed_subtask (MWTask *)
Friends
class MWTask
B. Task List Management
These functions are to manage the list of Tasks. MW provides default useful functionality for managing the list of tasks.
void set_task_key_function (MWKey(*)(MWTask *))
Sets the function that MWDriver users to get the `key` for a task.
int set_task_add_mode (MWTaskAdditionMode)
Set the mode you wish for task addition.
int set_task_retrieve_mode (MWTaskRetrievalMode)
Set the mode you wish for task retrieval.
int sort_task_list (void)
This sorts the task list by the key that is set.
int delete_tasks_worse_than (MWKey)
int get_number_tasks ()
returns the number of tasks on the todo list.
int getNumWorkers ()
int get_number_running_tasks ()
returns the number of running tasks.
int print_task_keys (void)
(Mostly for debugging) -- Prints the task keys in the todo list
void workClasses_set (int num)
Set number of workclasses.
int workClasses_get ()
Get the number of workclasses.
int stop_work ()
Stop the worker working on this task container and send it a new task container. This should only be called in act_on_completed_task(MWTask*)
int workClasses_getworkers (int num)
get number of workers in the specified work class
int workClasses_gettasks (int num)
get number of tasks in the specified work class
int refreshWorkers (int i, MWREFRESH_TYPE)
Pack new init data for all workers in group i.
void addTask (MWTask *)
Add a task to the list.
void addTasks (int, MWTask **)
void addSortedTasks (int n, MWTask **add_tasks)
. task timeout policy.
MW provides a mechanism for performing tasks on workers that are potentially `lost`. If the RMComm fails to notify MW of a worker going away in a timely fashion, the state of the computing platform and MW's vision of its state may become out of synch. In order to make sure that all tasks are done in a timely fashion, the user may set a time limit after which a task running on a `lost` worker may be rescheduled.
void set_worker_timeout_limit (double timeout_limit, int timeout_frequency)
E. Checkpoint Handling Functions
These are logical checkpoint handling functions. They are virtual, and are entirely application-specific. In them, the user must save the `state` of the application to permanent storage (disk). To do this, you need to:
{itemize} Implement the methods write_master_state() and read_master_state() in your derived MWDriver app. Implement the methods write_ckpt_info() and read_ckpt_info() in your derived MWTask class. {itemize}
Then MWDriver does the rest for you. When checkpoint() is called (see below) it opens up a known filename for writing. It passes the file pointer of that file to write_master_state(), which dumps the `state` of the master to that fp. Here `sate` includes all the variables, info, etc of YOUR CLASS THAT WAS DERIVED FROM MWDRIVER. All state in MWDriver.C is taken care of (there's not much). Next, checkpoint will walk down the running queue and the todo queue and call each member's write_ckpt_info().
Upon restart, MWDriver will detect the presence of the checkpoint file and restart from it. It calls read_master_state(), which is the inverse of write_master_state(). Then, for each task in the checkpoint file, it creates a new MWTask, calls read_ckpt_info() on it, and adds it to the todo queue.
We start from there and proceed as normal.
One can set the `frequency` that checkpoint files will be written (using set_checkpoint_frequency()). The default frequency is zero - no checkpointing. When the frequency is set to n, every nth time that act_on_completed_task gets called, we checkpoint immediately afterwards. If your application involves `work steps`, you probably will want to leave the frequency at zero and call checkpoint yourself at the end of a work step.
int MIN_IN_MEM
int NUM_IN_MEM_LO
int NUM_IN_MEM_HI
int MAX_IN_MEM
void checkpoint ()
void restart_from_ckpt ()
int set_checkpoint_frequency (int freq)
int set_checkpoint_time (int secs)
virtual void write_master_state (FILE *fp)
virtual void read_master_state (FILE *fp)
bool swap_out_todo_tasks (int num_in_mem=2048, int max_in_mem=204800, double max_key=DBL_MAX)
bool swap_in_todo_tasks (int min_in_mem=256, int num_in_mem=25600)
bool is_TODO_empty ()
MWTask * read_mem_task (MWList< MWTask > *tasks)
MWTask * read_file_task (FILE *f)
void write_task (FILE *f, MWTask *t)
virtual MWTask * gimme_a_task ()=0
Internal Task List Routines
These methods and data are responsible for managing the list of tasks to be done
MWKey(* task_key)(MWTask *)
MWTask * get_todo_head ()
void give_work (MWWorkerID *w, MWTask *t)
Worker management methods
These methods act on the list of workers (or specifically) ID's of workers, that the driver knows about.
void printWorkers ()
Prints the available workers.
MWWorkerID * get_workers_head ()
int numWorkers ()
Counts the existing workers.
int numWorkers (int arch)
Counts the number of workers in the given arch class.
int numWorkersInState (int ThisState)
Counts the number of workers in the given state.
MWKey return_best_todo_keyval (void)
Returns the value (only) of the best key in the Todo list.
MWKey return_best_running_keyval (void)
Returns the best value (only) of the best key in the Running list.
Detailed Description
This class is responsible for managing an application in an opportunistic environment. The goal is to be completely fault - tolerant, dealing with all possiblities of host (worker) problems. To do this, the MWDriver class manages a set of tasks and a set of workers. It monitors messages about hosts coming up and going down, and assigns tasks appropriately.
This class is built upon some sort of resource management and 
message passing lower layer.  Previously, it was built directly 
on top of Condor - PVM, but the interface to that has been 
abstracted away so that it can use any facility that provides 
for resource management and message passing.  See the abstract
MWRMComm class for details of this lower layer.  When interfacing
with this level, you'll have use the RMC object that's a static
member of the MWDriver, MWTask, and MWWorker class.  
To implement an application, a user must derive a class from this base class and implement the following methods:
get_userinfo()
setup_initial_tasks()
pack_worker_init_data()
act_on_completed_task()
For a higher level of control regarding distribution of tasks to workers, 
tasks and workers may be enrolled to workclasses/groups by calling the
following methods:

- MWWorkerID::addGroup()
- MWWorkerID::deleteGroup()
- MWTask::addGroup()
- MWTask::deleteGroup()

These methods can be called by an application using workclasses:

- workClasses_set()  (Required)
- workClasses_get()
- workClasses_gettasks()
- workClasses_getworkers()

To enroll workers in workclasses, there are two options:
- act_on_starting_worker() can be implemented to enroll workers to 
workclasses based on MWWorkerID info at the start of execution
- pack_worker_init_data() can be implemented to enroll workers. When used 
in conjunction with refreshWorkers(), can change workclass of workers in the        middle of execution.    
Similar application dependent methods must be implemented for the `Task` of work to be done and the `Worker` who performs the tasks.
See also
MWTask
MWWorker
MWRMComm
Author
Mike Yoder, Jeff Linderoth, Jean-Pierre Goux, Sanjeev Kulkarni
Constructor & Destructor Documentation
 MWDriver()
MWDriver::~MWDriver () [virtual]
Destructor - walks through lists of tasks & workers and deletes them.
Member Function Documentation
act_on_completed_subtask()
virtual MWReturn MWDriver::act_on_completed_subtask (MWTask *) [inline], [protected], [virtual]
This function performs an action that happens once the Driver receives notification of a completed subtask.
References addSortedTasks(), addTask(), addTasks(), checkpoint(), delete_tasks_worse_than(), get_number_running_tasks(), get_number_tasks(), handle_benchmark(), handle_checksum(), handle_hostdel(), handle_hostresume(), handle_hostsuspend(), handle_taskexit(), print_task_keys(), refreshWorkers(), restart_from_ckpt(), set_checkpoint_frequency(), set_checkpoint_time(), set_machine_ordering_policy(), set_suspension_policy(), set_task_add_mode(), set_task_key_function(), set_task_retrieve_mode(), set_worker_timeout_limit(), sort_task_list(), stop_work(), workClasses_get(), workClasses_gettasks(), workClasses_getworkers(), and workClasses_set().
Referenced by go().
act_on_completed_task()
virtual MWReturn MWDriver::act_on_completed_task (MWTask *) [protected], [pure virtual]
This function performs actions that happen once the Driver receives notification of a completed task. You will need to cast the MWTask * to a pointer of the Task type derived for your application. For example
            \begin{verbatim}
            My_Task *dt = dynamic_cast<My_Task *> ( t );
            assert( dt );     
            \end{verbatim}
Referenced by handle_hostresume().
act_on_starting_worker()
MWReturn MWDriver::act_on_starting_worker (MWWorkerID * w) [protected], [virtual]
This is called once the Worker is done with the TaskContainer.
Put the logic for this in MWDriver This function should be implemented by the application to assign the workClass number to the worker if it is doing intelligent work scheduling.
Referenced by delete_tasks_worse_than().
addSortedTasks()
void MWDriver::addSortedTasks (int n, MWTask ** add_tasks) [protected]
This will add a list of tasks that are sorted by key. Efficiency can be greatly improved by using this function
References MWTask::addGroup(), MWRMComm::exit(), MWWorker::go(), MWRMComm::hostadd(), MWTask::number, RMC, and task_key.
Referenced by act_on_completed_subtask().
addTasks()
void MWDriver::addTasks (int n, MWTask ** add_tasks) [protected]
Add a bunch of tasks to the list. You do this by making an array of pointers to MWTasks and giving that array to this function. The MWDriver will take over memory management for the MWTasks, but not for the array of pointers, so don't forget to delete [] it!
References MWTask::addGroup(), MWRMComm::exit(), MWTask::number, and RMC.
Referenced by act_on_completed_subtask(), and go().
checkpoint()
void MWDriver::checkpoint ()
This function writes the current state of the job to disk. See the section header to see how it does this.
See also
MWTask
References RMC, MWTask::taskType, MWRMComm::write_checkpoint(), MWTask::write_ckpt_info(), and write_master_state().
Referenced by act_on_completed_subtask(), handle_hostresume(), restart_from_ckpt(), swap_in_todo_tasks(), and swap_out_todo_tasks().
delete_tasks_worse_than()
int MWDriver::delete_tasks_worse_than (MWKey key)
This deletes all tasks in the task list with a key worse than the one specified
References act_on_starting_worker(), MWRMComm::get_num_exec_classes(), MWRMComm::hostaddlogic(), MWTask::number, numWorkers(), MWTask::printself(), MWRMComm::removeWorker(), RMC, and task_key.
Referenced by act_on_completed_subtask().
get_benchmark_task()
MWTask* MWDriver::get_benchmark_task () [inline]
get the benchmark task
Referenced by handle_checksum(), and refreshWorkers().
get_todo_head()
MWTask * MWDriver::get_todo_head ()
This is Jeff's nasty addition so that he can get access to the tasks on the master
get_userinfo()
virtual MWReturn MWDriver::get_userinfo (int argc, char * argv[]) [protected], [pure virtual]
This function is called to read in all information specific to a user's application and do any initialization on this information.
Referenced by go().
get_workers_head()
MWWorkerID * MWDriver::get_workers_head ()
Another terrible addition so that Jeff can print out the worker list in his own format
References MWRMComm::get_num_exec_classes(), get_number_running_tasks(), get_number_tasks(), MWRMComm::initsend(), numWorkersInState(), RMC, MWRMComm::send(), and MWRMComm::set_target_num_workers().
gimme_a_task()
virtual MWTask* MWDriver::gimme_a_task () [pure virtual]
It's really annoying that the user has to do this, but they do. The thing is, we have to make a new task of the user's derived type when we read in the checkpoint file.
If your application coredumps when trying to restart from a checkpoint, it might be becasue you haven't implemented this function.
{verbatim} MWTask* gimme_a_task() { return new <your derived=`` task=`` class>=``>; } {verbatim}
Referenced by read_master_state(), restart_from_ckpt(), and swap_in_todo_tasks().
go() [1/2]
void MWDriver::go (int argc, char * argv[])
This method runs the entire fault-tolerant application in the condor environment. What is really does is call setup_master(), then master(), then printresults(), and then ends. See the other functions for details.
References act_on_completed_subtask(), addTasks(), MWRMComm::bufinfo(), MWRMComm::exit(), get_userinfo(), handle_benchmark(), handle_checksum(), handle_hostdel(), handle_hostresume(), handle_hostsuspend(), handle_taskexit(), MWRMComm::init_beginning_workers(), MWRMComm::initsend(), is_TODO_empty(), printresults(), printWorkers(), MWRMComm::recv(), MWRMComm::restart_beginning_workers(), restart_from_ckpt(), RMC, MWRMComm::send(), MWRMComm::setup(), setup_initial_tasks(), MWRMComm::start_worker(), MWRMComm::unpack(), and workClasses_set().
go() [2/2]
void MWDriver::go () [inline]
This version of go simply calls go(0, NULL).
References go(), and printresults().
Referenced by go().
handle_benchmark()
MWReturn MWDriver::handle_benchmark (MWWorkerID * w) [virtual]
Here, we get back the benchmarking results, which tell us something about the worker we've got. Also, we could get some sort of error back from the worker at this stage, in which case we remove it.
References MWRMComm::initsend(), MWTask::number, MWRMComm::pack(), pack_driver_task_data(), MWTask::pack_work(), MWRMComm::removeWorker(), RMC, MWRMComm::send(), MWTask::taskType, MWRMComm::unpack(), and MWTask::worker.
Referenced by act_on_completed_subtask(), and go().
handle_checksum()
void MWDriver::handle_checksum () [virtual]
Routine to handle when the communication layer says that a checksum error happened. If the underlying Communitor gives a reliably reliable communication then this messge need not be generated. But for some Communicators like MW-File we may need some thing like this.
References get_benchmark_task(), MWRMComm::initsend(), MWRMComm::pack(), MWTask::pack_work(), pack_worker_init_data(), MWRMComm::removeWorker(), RMC, MWRMComm::send(), and MWRMComm::who().
Referenced by act_on_completed_subtask(), and go().
handle_hostdel()
void MWDriver::handle_hostdel () [virtual]
This is what gets called when a host goes away. We figure out who died, remove that worker from our records, remove its task from the running queue (if it was running one) and put that task back on the todo list.
References RMC, and MWRMComm::who().
Referenced by act_on_completed_subtask(), and go().
handle_hostresume()
void MWDriver::handle_hostresume () [virtual]
Here's where you go when a host gets resumed. Usually, you do nothing...but it's nice to know...
References act_on_completed_task(), checkpoint(), MWTask::cpu_time, MWTask::deleteGroup(), MWTask::number, RMC, task_key, MWTask::taskType, MWRMComm::unpack(), MWTask::unpack_results(), MWRMComm::who(), MWTask::worker, and MWTask::working_time.
Referenced by act_on_completed_subtask(), and go().
handle_hostsuspend()
void MWDriver::handle_hostsuspend () [virtual]
Implements a suspension policy. Currently either DEFAULT or REASSIGN, depending on how suspensionPolicy is set.
References MWTask::number, RMC, and MWRMComm::who().
Referenced by act_on_completed_subtask(), and go().
handle_taskexit()
void MWDriver::handle_taskexit () [virtual]
We do basically the same thing as handle_hostdel(). One might {think} that we could restart something on that host; in practice, however -- especially with the Condor-PVM RMComm implementation -- it means that the host has gone down, too. We put that host's task back on the todo list.
References MWRMComm::removeWorker(), RMC, and MWRMComm::who().
Referenced by act_on_completed_subtask(), and go().
is_TODO_empty()
bool MWDriver::is_TODO_empty ()
See whether we still have TODO tasks
Referenced by go(), and read_master_state().
pack_driver_task_data()
virtual void MWDriver::pack_driver_task_data (void) [inline], [protected], [virtual]
OK, This one is not pure virtual either, but if you have some `driver` data that is conceptually part of the task and you wish not to replicate the data in each task, you can pack it in a message buffer by implementing this function. If you do this, you must implement a matching unpack_worker_task_data() function.
Referenced by handle_benchmark().
pack_worker_init_data()
virtual MWReturn MWDriver::pack_worker_init_data (void) [protected], [pure virtual]
A common theme of Master-Worker applications is that there is a base amount of `initial` data defining the problem, and then just incremental data defining `Tasks` to be done by the Workers.
This one packs all the user's initial data. It is unpacked int the worker class, in unpack_init_data().
Referenced by handle_checksum(), and refreshWorkers().
printresults()
void MWDriver::printresults () [virtual]
Prints the Results. Applications may re-implement this to print their application specific results. It is meant to be over-ridden.
References RMC.
Referenced by go().
read_master_state()
virtual void MWDriver::read_master_state (FILE * fp) [inline], [virtual]
Here, you read in the 'state' of the driver from fp. Note that this is the reverse of write_master_state().
Parameters
fp A file pointer that has been opened for reading.
References gimme_a_task(), is_TODO_empty(), MIN_IN_MEM, swap_in_todo_tasks(), and swap_out_todo_tasks().
Referenced by restart_from_ckpt().
register_benchmark_task()
void MWDriver::register_benchmark_task (MWTask * t) [inline]
register the task that will be used for benchmarking.
restart_from_ckpt()
void MWDriver::restart_from_ckpt ()
This function does the inverse of checkpoint. It opens the checkpoint file, calls read_master_state(), then, for each task class in the file, creates a MWTask, calls read_ckpt_info on it, and adds that class to the todo list.
References checkpoint(), gimme_a_task(), MWTask::number, print_task_keys(), MWTask::printself(), MWRMComm::read_checkpoint(), MWTask::read_ckpt_info(), read_master_state(), RMC, set_task_add_mode(), sort_task_list(), swap_out_todo_tasks(), task_key, and MWTask::write_ckpt_info().
Referenced by act_on_completed_subtask(), and go().
set_checkpoint_frequency()
int MWDriver::set_checkpoint_frequency (int freq)
This function sets the frequency with with checkpoints are done. It returns the former frequency value. The default frequency is zero (no checkpoints). If the frequency is n, then a checkpoint will occur after the nth call to act_on_completed_task(). A good place to set this is in get_userinfo().
Parameters
freq The frequency to set checkpoints to.
Returns
The former frequency value.
Referenced by act_on_completed_subtask().
set_checkpoint_time()
int MWDriver::set_checkpoint_time (int secs)
Set a time-based frequency for checkpoints. The time units are in seconds. A value of 0 `turns off` time-based checkpointing. Time-based checkpointing cannot be `turned
on` unless the checkpoint_frequency is set to 0. A good place to do this is in get_userinfo().
Parameters
secs Checkpoint every `secs` seconds
Returns
The former time frequency value.
Referenced by act_on_completed_subtask().
set_suspension_policy()
void MWDriver::set_suspension_policy (MWSuspensionPolicy policy)
Set the policy to use when suspending. Currently this can be either DEFAULT or REASSIGN
Referenced by act_on_completed_subtask().
set_worker_timeout_limit()
void MWDriver::set_worker_timeout_limit (double timeout_limit, int timeout_frequency)
Sets the timeout_limit and turn worker_timeout to 1
References MWTask::number, and MWTask::taskType.
Referenced by act_on_completed_subtask().
setup_initial_tasks()
virtual MWReturn MWDriver::setup_initial_tasks (int * n, MWTask *** task) [protected], [pure virtual]
This function must return a number n > 0 of pointers to Tasks to `jump start` the application.
The MWTasks pointed to should be of the task type derived for your application
Referenced by go().
swap_in_todo_tasks()
bool MWDriver::swap_in_todo_tasks (int min_in_mem = 256, int num_in_mem = 25600)
When swapping in, we first read first num_in_mem (or all tasks if not so many tasks in swap file) tasks from the swap file, create tasks and append to a newly created list. Then we sorted insert the existing tasks in memory into the new list. When done, switch the list and file.
If the old TODO list is not too small (>num_in_mem), won't swap in. Return value indicates whether the swapping is successful or not.
References checkpoint(), gimme_a_task(), and task_key.
Referenced by read_master_state().
swap_out_todo_tasks()
bool MWDriver::swap_out_todo_tasks (int num_in_mem = 2048, int max_in_mem = 204800, double max_key = DBL_MAX)
TODO Tasks Swapping
References checkpoint(), and task_key.
Referenced by read_master_state(), and restart_from_ckpt().
unpack_worker_initinfo()
virtual void MWDriver::unpack_worker_initinfo (MWWorkerID * w) [inline], [protected], [virtual]
This one unpacks the `initial` information sent to the driver once the worker initializes.
Potential `initial` information that might be useful is... {itemize} Information on the worker characteristics etc... Information on the bandwith between MWDriver and worker {itemize}
These sorts of things could be useful in building some scheduling intelligence into the driver.
Referenced by refreshWorkers().
write_master_state()
virtual void MWDriver::write_master_state (FILE * fp) [inline], [virtual]
Here you write out all 'state' of the driver to fp.
Parameters
fp A file pointer that has been opened for writing.
Referenced by checkpoint().
Member Data Documentation
MIN_IN_MEM
int MWDriver::MIN_IN_MEM
Swap the unused part of the (sorted and indexed) TODO list onto disk (file name: TODO_tasks.id), so that the TODO tasks with smaller key values are kept in memory, and others are kept in a file. When there are too many tasks in memory, we swap most of them out; when there are too few tasks in memory, we swap in more. The MW application will be done only when all TODO tasks are done. When checkpointing, it only saves TODO tasks in memory, and the pointers (the file name) to the swap file.
To help swapping in tasks, we will record the number of tasks swapped in at the beginning of the file, and skip then when read to swap file. The num_to_skip is initially set to 0.
The swap file for TODO tasks is fully-sorted, and looks like:
num_to_skip trash_task1 trash_task2 ... ... task1 task2 ... ... task[num_tasks]When swapping out, we walk through the sorted TODO list, keep the first num_in_mem tasks in memory (copy into a newly created list). For the rest of the list, merge it in order with existing tasks in the file TODO_tasks, and write them into a newly created swap file. Tasks in swap file whose key values are larger than max_key are removed. When done, delete the old TODO list and swap file, switch to the new ones.
If the old TODO list is not too large (<max_in_mem), won't swap out. Return value indicates whether the swapping is successful or not.
Referenced by MWDriver(), and read_master_state().
RMC
MWRMComm* MWDriver::RMC [static]
A static instance of our Resource Management / Communication class. It's a member of this class because that way derived classes can use it easily; it's static because there should only be one instance EVER. The instance of RMC in the MWTask class is actually a pointer to this one...
Referenced by addSortedTasks(), addTasks(), checkpoint(), delete_tasks_worse_than(), get_workers_head(), go(), handle_benchmark(), handle_checksum(), handle_hostdel(), handle_hostresume(), handle_hostsuspend(), handle_taskexit(), printresults(), refreshWorkers(), restart_from_ckpt(), and stop_work().
task_key
MWKey(* MWDriver::task_key) (MWTask *) [protected]
A pointer to a (user written) function that takes an MWTask and returns the `key` for this task. The user is allowed to change the `key` by simply changing the function
Referenced by addSortedTasks(), delete_tasks_worse_than(), handle_hostresume(), MWDriver(), print_task_keys(), restart_from_ckpt(), return_best_running_keyval(), return_best_todo_keyval(), set_task_key_function(), set_task_retrieve_mode(), sort_task_list(), swap_in_todo_tasks(), and swap_out_todo_tasks().
The documentation for this class was generated from the following files:
MWDriver.h
MWDriver.C